In [2]:
import numpy as np

# Create

In [6]:
# 2 → Number of blocks (Depth)
# 3 → Number of rows
# 4 → Number of columns
# in any shpae ,the last two determines row and column
# and before that all determines the level of depth and sub groups
data = np.random.rand(2,3,4)
zeroes = np.zeros((1,2,3))
ones = np.ones((1,2,3))
full = np.full((1,2,3),4)

In [8]:
data

array([[[0.21637241, 0.53779773, 0.07590305, 0.11961912],
        [0.17452313, 0.85961848, 0.38219156, 0.14758913],
        [0.96378325, 0.44816952, 0.10239716, 0.093716  ]],

       [[0.84091538, 0.71482653, 0.26022193, 0.4316831 ],
        [0.59962818, 0.96885768, 0.04460327, 0.24889724],
        [0.49366102, 0.17529761, 0.0120056 , 0.34940802]]])

In [9]:
list_arr = [[1,2,3],[1,2,3]]
np.array(list_arr)

array([[1, 2, 3],
       [1, 2, 3]])

### Read

In [10]:
shape = data.shape
size = data.size
types = data.dtype

In [25]:
### slicing
# arr[start1:stop1:step1, start2:stop2:step2, ...]
# Slicing works by specifying start:stop:step along each dimension.

# same output
print(data[0,:,:])
print(data[0])

# cols of 1 firt row of first 1 group
print(data[0,0,:])
print(data[0][0][0])

[[0.21637241 0.53779773 0.07590305 0.11961912]
 [0.17452313 0.85961848 0.38219156 0.14758913]
 [0.96378325 0.44816952 0.10239716 0.093716  ]]
[[0.21637241 0.53779773 0.07590305 0.11961912]
 [0.17452313 0.85961848 0.38219156 0.14758913]
 [0.96378325 0.44816952 0.10239716 0.093716  ]]
[0.21637241 0.53779773 0.07590305 0.11961912]
0.2163724121855507


### Update

In [24]:
### for maths
# for maths we can use the methods present in the np
# like max, min , dot,max, avg, matrix sum, mul

In [29]:
data[0][0][0] = 12
data.sort()
data

array([[[ 0.11961912,  0.53779773, 12.        , 12.        ],
        [ 0.14758913,  0.17452313,  0.38219156,  0.85961848],
        [ 0.093716  ,  0.10239716,  0.44816952,  0.96378325]],

       [[ 0.26022193,  0.4316831 ,  0.71482653,  0.84091538],
        [ 0.04460327,  0.24889724,  0.59962818,  0.96885768],
        [ 0.0120056 ,  0.17529761,  0.34940802,  0.49366102]]])

In [37]:
# logic behind reshapping
# the total multiplication should be equal to data.size
# we can mention -1 atmost 1 for unknow dimension telling the dimension
# of that depth can be anything
# here the size is 24 ; so 3*8 = 24
data.reshape(3,8,-1)

array([[[ 0.11961912],
        [ 0.53779773],
        [12.        ],
        [12.        ],
        [ 0.14758913],
        [ 0.17452313],
        [ 0.38219156],
        [ 0.85961848]],

       [[ 0.093716  ],
        [ 0.10239716],
        [ 0.44816952],
        [ 0.96378325],
        [ 0.26022193],
        [ 0.4316831 ],
        [ 0.71482653],
        [ 0.84091538]],

       [[ 0.04460327],
        [ 0.24889724],
        [ 0.59962818],
        [ 0.96885768],
        [ 0.0120056 ],
        [ 0.17529761],
        [ 0.34940802],
        [ 0.49366102]]])

In [ ]:
"""
If axis=None, everything is flattened to 1D first, then appended.
If axis=0, new data must have the same number of columns as the original.
If axis=1, new data must have the same number of rows as the original.
"""
# New data must have shape (1, 2, 4)
new_data = np.array([[
    [10, 20, 30, 40],
    [50, 60, 70, 80]
]])

# returned new array
new_zeroes = np.append(zeroes, new_data, axis=0) #cols must be same as with new_data
# row added so needs to add on more row to the new_data
# to append new_data to new_zeroes along axis 1
new_data = new_data.reshape(2,1,4)
new_zeroes = np.append(new_zeroes, new_data, axis=1)

(2, 2, 4)
(1, 2, 4)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 4 and the array at index 1 has size 1